# Generated by Django 5.2.9 on 2026-01-04 19:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT(0 0)', geography=True, srid=4326),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('FULL', 'Full'), ('CLOSED', 'Closed')], default='OPEN', max_length=10),
        ),
    ]
